### ISSUE TITLE
Graph inspector showing multiselect message depite one node selected

### ISSUE THREAD

**Issue by leissler** [Gentlymad-Studios/NewGraph#1]
If you select 2 (or more) nodes, the inspector will correctly show a message that multiple nodes are selected.
However, when you deselect all nodes but one, the message is still there, claiming that multiple nodes are selected (the number in the message also doesn't change when deselecting).
The expected behavior is that the inspector shows the node's contents as soon as only one node is selected, even if multiple were selected before.

**Comment by Doppelkeks** [comment]
Fixed in 0.2.4
