### ISSUE TITLE
Doesn't work in 2022.3

### ISSUE THREAD

**Issue by kajloevesijn** [Gentlymad-Studios/NewGraph#37]
problem: newgraph doesn't show up under tools.

how to reproduce:

1. create a new project
2. follow the official instructions on unity version 2022.3

**Comment by akatriel** [comment]
Works fine for me...

**Comment by Doppelkeks** [comment]
> problem: newgraph doesn't show up under tools.
> 
> how to reproduce:
> 
> 1. create a new project
> 2. follow the official instructions on unity version 2022.3

Hi, did you use the sample package, to get the menu entry?
