### ISSUE TITLE
Closing/re-opening project ScriptableGraphModel.asset not found

### ISSUE THREAD

**Issue by akatriel** [Gentlymad-Studios/NewGraph#40]
Produced in Unity 2023.2.3.16f1
Upon closing and re-opening project the AssetDatabase appears to lose the reference to the ScriptableGraphModel.asset with the following error:

> settings blueprint could not be resolved! Path: Assets/Scripts/Editor/NewGraph/Editor/Settings/GraphSettings.asset GUID: 015778251503b3c44a2b9dfc3a36ad10
UnityEngine.Debug:LogError (object)
NewGraph.GraphSettingsSingleton:get_BlueprintSettings () (at Assets/Scripts/Editor/NewGraph/Editor/Settings/GraphSettingsSingleton.cs:34)
NewGraph.GraphSettingsSingleton:get_Settings () (at Assets/Scripts/Editor/NewGraph/Editor/Settings/GraphSettingsSingleton.cs:55)
NewGraph.GraphWindow:InitializeWindowBase (System.Type) (at Assets/Scripts/Editor/NewGraph/Editor/Views/GraphWindow.cs:80)
WindowInitializer.WindowInitializer:OpenWindow () (at Assets/Scripts/Editor/JobClassGraph/WindowInitializer.cs:12)

`WindowInitializer` was moved out of the Sample folder to a Scripts > Editor folder but has been unchanged:
```
namespace WindowInitializer {
	public class WindowInitializer {
		/// <summary>
		/// Here you can customize where the graph window menu should appear
		/// </summary>
		[MenuItem("Tools/" + nameof(GraphWindow))]
		static void OpenWindow() {
			// Here you can define what type of graph model you would like to use.
			GraphWindow.InitializeWindowBase(typeof(ScriptableGraphModel));
		}
	}
}
```
Any help appreciated!

**Comment by Doppelkeks** [comment]
Did you install NewGraph as a package or did you [clone it locally](https://github.com/Gentlymad-Studios/NewGraph/wiki/1.-Installation-%F0%9F%8E%AF)? Sadly, there is a Unity bug the results in broken references when using git repos as packages. :/

**Comment by akatriel** [comment]
OdinSerializer was installed as a package, however, GraphViewBase and New Graph were cloned locally into Assets > Scripts > Editor.

**Comment by Doppelkeks** [comment]
Hey, New Graph has a runtime and an Editor portion so it needs to sit directly in the Assets Folder or insides a Plugins folder, so maybe that is part of the problem 🙂

**Comment by akatriel** [comment]
Unfortunately, the error still exists even after completely removing it from the project and then re-copying the libraries to the Assets folder.

**Comment by akatriel** [comment]
Just to clarify, I think the major issue is the Blueprint Settings:
```
settings blueprint could not be resolved! Path: Assets/NewGraph/Editor/Settings/GraphSettings.asset GUID: 015778251503b3c44a2b9dfc3a36ad10
UnityEngine.Debug:LogError (object)
NewGraph.GraphSettingsSingleton:get_BlueprintSettings () (at Assets/NewGraph/Editor/Settings/GraphSettingsSingleton.cs:34)
NewGraph.GraphSettingsSingleton:get_BlueprintSettings () (at Assets/NewGraph/Editor/Settings/GraphSettingsSingleton.cs:29)
NewGraph.GraphSettingsSingleton:get_Settings () (at Assets/NewGraph/Editor/Settings/GraphSettingsSingleton.cs:55)
NewGraph.GraphSettingsProvider:CreateMyCustomSettingsProvider () (at Assets/NewGraph/Editor/Settings/GraphSettingsProvider.cs:77)
UnityEditor.SettingsWindow:OpenProjectSettings ()
```
Deleting the GraphSettings.asset file and reloading the editor, also not fixing the issue. Changed settings not being saved/reloaded.
