### ISSUE TITLE
Double-click on GraphModel asset does not open graph

### ISSUE THREAD

**Issue by leissler** [Gentlymad-Studios/NewGraph#7]
With a GraphWindow open and double-clicking on a GraphModel-asset that is not currently shown (or alternatively clicking the open button in the Unity-Inspector), the new GraphModel-asset is not opened in the existing window.
Even though there is a "Load" button in the GraphView itself, this would be expected behavior.

**Comment by Doppelkeks** [comment]
Fixed in 0.3.1
