### ISSUE TITLE
Choosing "None" value in a nodes GameObject-type field does not properly refresh the field

### ISSUE THREAD

**Issue by leissler** [Gentlymad-Studios/NewGraph#9]
When having a node-field of a Unity-scene-reference type (e.g. a GameObject variable for referencing Prefabs) with either DisplayType.NodeView or DisplayType.BothViews in its GraphDisplay attribute, it is correctly possible to choose a value from Unity's selector box. However, when choosing the "None" value, the field in the node does not update to the correct value but instead stays at the last selected non-empty value.
With DisplyType.BothViews enabled, the field with the open selector box has this faulty behavior, while the other corresponding field (inspector or nodeview) does update correctly.

![test5](https://user-images.githubusercontent.com/243927/229923218-4cb28540-3018-470f-9288-8aa146804449.gif)

The video shows that de-selecting the node and then selecting it correctly refreshes the value of the field.

**Comment by Doppelkeks** [comment]
This is a UnityBug related to [SerializeReference] & UIElements

This video showcases the same bug happening in a default unity inspector

https://user-images.githubusercontent.com/530629/234556840-06da1b82-23d8-4afe-971b-5d9197041e13.mp4



Will update as soon as my bug report was confirmed and there is a public issuetracker link.

**Comment by Doppelkeks** [comment]
This issue has been reported by Unity to have been fixed.

**Comment by leissler** [comment]
Do I understand correctly that you will need Unity 2023.3.0+ to have this fix included?
Don't they backport such things?
